services:
  db_postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
