services:
  db_postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=apollogram
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
